In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv('1b_5yrs_filtered.csv')
df2 = pd.read_csv('2b_5yrs_filtered.csv')
df3 = pd.read_csv('3b_5yrs_filtered.csv')

In [3]:
df1['Source'] = '1 Bedroom'
df2['Source'] = '2 Bedroom'
df3['Source'] = '3 Bedroom'

In [8]:
combined_df = pd.concat([df1, df2, df3], ignore_index=True)
combined_df = combined_df[['Source'] + [col for col in combined_df.columns if col != 'Source']]
print(combined_df)

       Source  RegionID  SizeRank     RegionName RegionType StateName State  \
0   1 Bedroom      6181         0       New York       city        NY    NY
1   1 Bedroom     12447         1    Los Angeles       city        CA    CA
2   1 Bedroom     39051         2        Houston       city        TX    TX
3   1 Bedroom     17426         3        Chicago       city        IL    IL
4   1 Bedroom     40326         6        Phoenix       city        AZ    AZ
5   1 Bedroom     18959         7      Las Vegas       city        NV    NV
6   1 Bedroom     38128         9         Dallas       city        TX    TX
7   1 Bedroom     20330        17  San Francisco       city        CA    CA
8   1 Bedroom     12700        20          Miami       city        FL    FL
9   1 Bedroom     11093        23         Denver       city        CO    CO
10  1 Bedroom     16037        24        Seattle       city        WA    WA
11  1 Bedroom     44269        29         Boston       city        MA    MA
12  1 Bedroom     37211        37        Atlanta       city        GA    GA
13  1 Bedroom      5983        53    Minneapolis       city        MN    MN
14  2 Bedroom      6181         0       New York       city        NY    NY
15  2 Bedroom     12447         1    Los Angeles       city        CA    CA
16  2 Bedroom     39051         2        Houston       city        TX    TX
17  2 Bedroom     17426         3        Chicago       city        IL    IL
18  2 Bedroom     40326         6        Phoenix       city        AZ    AZ
19  2 Bedroom     18959         7      Las Vegas       city        NV    NV
20  2 Bedroom     38128         9         Dallas       city        TX    TX
21  2 Bedroom     20330        17  San Francisco       city        CA    CA
22  2 Bedroom     12700        20          Miami       city        FL    FL
23  2 Bedroom     11093        23         Denver       city        CO    CO
24  2 Bedroom     16037        24        Seattle       city        WA    WA
25  2 Bedroom     44269        29         Boston       city        MA    MA
26  2 Bedroom     37211        37        Atlanta       city        GA    GA
27  2 Bedroom      5983        53    Minneapolis       city        MN    MN
28  3 Bedroom      6181         0       New York       city        NY    NY
29  3 Bedroom     12447         1    Los Angeles       city        CA    CA
30  3 Bedroom     39051         2        Houston       city        TX    TX
31  3 Bedroom     17426         3        Chicago       city        IL    IL
32  3 Bedroom     40326         6        Phoenix       city        AZ    AZ
33  3 Bedroom     18959         7      Las Vegas       city        NV    NV
34  3 Bedroom     38128         9         Dallas       city        TX    TX
35  3 Bedroom     20330        17  San Francisco       city        CA    CA
36  3 Bedroom     12700        20          Miami       city        FL    FL
37  3 Bedroom     11093        23         Denver       city        CO    CO
38  3 Bedroom     16037        24        Seattle       city        WA    WA
39  3 Bedroom     44269        29         Boston       city        MA    MA
40  3 Bedroom     37211        37        Atlanta       city        GA    GA
41  3 Bedroom      5983        53    Minneapolis       city        MN    MN

                                      Metro            CountyName  \
0     New York-Newark-Jersey City, NY-NJ-PA         Queens County
1        Los Angeles-Long Beach-Anaheim, CA    Los Angeles County
2      Houston-The Woodlands-Sugar Land, TX         Harris County
3        Chicago-Naperville-Elgin, IL-IN-WI           Cook County
4                 Phoenix-Mesa-Chandler, AZ       Maricopa County
5          Las Vegas-Henderson-Paradise, NV          Clark County
6           Dallas-Fort Worth-Arlington, TX         Dallas County
7        San Francisco-Oakland-Berkeley, CA  San Francisco County
8   Miami-Fort Lauderdale-Pompano Beach, FL     Miami-Dade County
9                Denver-Aurora-Lakewood, CO         Denver County
10              Seattle-Tacoma-Bellevue, WA           King County
11           Boston-Cambridge-Newton, MA-NH        Suffolk County
12     Atlanta-Sandy Springs-Alpharetta, GA         Fulton County
13  Minneapolis-St. Paul-Bloomington, MN-WI       Hennepin County
14    New York-Newark-Jersey City, NY-NJ-PA         Queens County
15       Los Angeles-Long Beach-Anaheim, CA    Los Angeles County
16     Houston-The Woodlands-Sugar Land, TX         Harris County
17       Chicago-Naperville-Elgin, IL-IN-WI           Cook County
18                Phoenix-Mesa-Chandler, AZ       Maricopa County
19         Las Vegas-Henderson-Paradise, NV          Clark County
20          Dallas-Fort Worth-Arlington, TX         Dallas County
21       San Francisco-Oakland-Berkeley, CA  San Francisco County
22  Miami-Fort Lauderdale-Pompano Beach, FL     Miami-Dade County
23               Denver-Aurora-Lakewood, CO         Denver County
24              Seattle-Tacoma-Bellevue, WA           King County
25           Boston-Cambridge-Newton, MA-NH        Suffolk County
26     Atlanta-Sandy Springs-Alpharetta, GA         Fulton County
27  Minneapolis-St. Paul-Bloomington, MN-WI       Hennepin County
28    New York-Newark-Jersey City, NY-NJ-PA         Queens County
29       Los Angeles-Long Beach-Anaheim, CA    Los Angeles County
30     Houston-The Woodlands-Sugar Land, TX         Harris County
31       Chicago-Naperville-Elgin, IL-IN-WI           Cook County
32                Phoenix-Mesa-Chandler, AZ       Maricopa County
33         Las Vegas-Henderson-Paradise, NV          Clark County
34          Dallas-Fort Worth-Arlington, TX         Dallas County
35       San Francisco-Oakland-Berkeley, CA  San Francisco County
36  Miami-Fort Lauderdale-Pompano Beach, FL     Miami-Dade County
37               Denver-Aurora-Lakewood, CO         Denver County
38              Seattle-Tacoma-Bellevue, WA           King County
39           Boston-Cambridge-Newton, MA-NH        Suffolk County
40     Atlanta-Sandy Springs-Alpharetta, GA         Fulton County
41  Minneapolis-St. Paul-Bloomington, MN-WI       Hennepin County

      2018-10-31  ...    2022-12-31    2023-01-31    2023-02-28    2023-03-31  \
0   5.557601e+05  ...  5.714553e+05  5.728410e+05  5.734557e+05  5.732841e+05
1   5.142191e+05  ...  5.963778e+05  5.939913e+05  5.880965e+05  5.807081e+05
2   9.802218e+04  ...  1.277090e+05  1.282693e+05  1.286578e+05  1.289426e+05
3   2.197033e+05  ...  2.304073e+05  2.304718e+05  2.303163e+05  2.307079e+05
4   1.375094e+05  ...  2.611448e+05  2.575616e+05  2.540055e+05  2.511728e+05
5   1.327441e+05  ...  2.026507e+05  1.992345e+05  1.963131e+05  1.941184e+05
6   1.226219e+05  ...  1.684544e+05  1.688819e+05  1.690018e+05  1.690011e+05
7   8.716047e+05  ...  7.923028e+05  7.822157e+05  7.731601e+05  7.669646e+05
8   2.553238e+05  ...  3.878828e+05  3.893009e+05  3.894522e+05  3.898728e+05
9   2.788363e+05  ...  3.421708e+05  3.410634e+05  3.396003e+05  3.382930e+05
10  4.783959e+05  ...  4.722636e+05  4.704375e+05  4.681093e+05  4.656853e+05
11  5.720090e+05  ...  5.893708e+05  5.889232e+05  5.873872e+05  5.856552e+05
12  2.107034e+05  ...  2.739594e+05  2.748079e+05  2.750544e+05  2.751851e+05
13  1.960331e+05  ...  1.947949e+05  1.939297e+05  1.930286e+05  1.923498e+05
14  7.006988e+05  ...  7.184954e+05  7.204842e+05  7.209588e+05  7.199955e+05
15  6.006962e+05  ...  7.654597e+05  7.596113e+05  7.490655e+05  7.374275e+05
16  1.247064e+05  ...  1.822989e+05  1.820074e+05  1.814396e+05  1.812109e+05
17  2.365305e+05  ...  2.772951e+05  2.768889e+05  2.768365e+05  2.777578e+05
18  1.871631e+05  ...  3.329178e+05  3.276320e+05  3.230784e+05  3.199752e+05
19  1.902303e+05  ...  2.906407e+05  2.859376e+05  2.818418e+05  2.786222e+05
20  1.629172e+05  ...  2.418646e+05  2.408394e+05  2.394483e+05  2.387246e+05
21  1.221098e+06  ...  1.229809e+06  1.212350e+06  1.196557e+06  1.184052e+06
22  3.124679e+05  ...  4.879718e+05  4.893112e+05  4.896464e+05  4.907371e+05
23  3.622726e+05  ...  4.809604e+05  4.781407e+05  4.751870e+05  4.730518e+05
24  6.337341e+05  ...  7.127065e+05  7.077061e+05  7.016706e+05  6.954431e+05
25  6.649518e+05  ...  7.240447e+05  7.220584e+05  7.195192e+05  7.179405e+05
26  2.748982e+05  ...  3.573257e+05  3.564287e+05  3.553685e+05  3.548460e+05
27  2.459565e+05  ...  2.797369e+05  2.788928e+05  2.781137e+05  2.773776e+05
28  6.736805e+05  ...  7.666966e+05  7.650197e+05  7.617803e+05  7.591085e+05
29  6.644513e+05  ...  9.025177e+05  8.938216e+05  8.808775e+05  8.673078e+05
30  1.666149e+05  ...  2.470508e+05  2.458555e+05  2.445236e+05  2.436390e+05
31  2.378089e+05  ...  2.937681e+05  2.927389e+05  2.925167e+05  2.931045e+05
32  2.432785e+05  ...  4.164044e+05  4.092056e+05  4.036418e+05  4.003632e+05
33  2.684481e+05  ...  3.996063e+05  3.932662e+05  3.880388e+05  3.842779e+05
34  1.914698e+05  ...  2.934506e+05  2.915027e+05  2.897321e+05  2.890385e+05
35  1.526989e+06  ...  1.588864e+06  1.563413e+06  1.541399e+06  1.523435e+06
36  3.667394e+05  ...  5.840246e+05  5.853600e+05  5.864061e+05  5.884972e+05
37  4.396248e+05  ...  6.002359e+05  5.966695e+05  5.933716e+05  5.909741e+05
38  7.747014e+05  ...  9.108926e+05  9.035749e+05  8.953314e+05  8.870108e+05
39  6.062882e+05  ...  7.183573e+05  7.149690e+05  7.117592e+05  7.105780e+05
40  2.506651e+05  ...  3.727829e+05  3.715049e+05  3.709173e+05  3.711583e+05
41  2.794067e+05  ...  3.337530e+05  3.329724e+05  3.328094e+05  3.328782e+05

      2023-04-30    2023-05-31    2023-06-30    2023-07-31    2023-08-31  \
0   5.715598e+05  5.707120e+05  5.713108e+05  5.713580e+05  5.703716e+05
1   5.757599e+05  5.734329e+05  5.735240e+05  5.762631e+05  5.812828e+05
2   1.291195e+05  1.291779e+05  1.292591e+05  1.293966e+05  1.297150e+05
3   2.320083e+05  2.339844e+05  2.360504e+05  2.379112e+05  2.398344e+05
4   2.498993e+05  2.492098e+05  2.493416e+05  2.502807e+05  2.523483e+05
5   1.927692e+05  1.919249e+05  1.918671e+05  1.926424e+05  1.939728e+05
6   1.689275e+05  1.688375e+05  1.691363e+05  1.698411e+05  1.711389e+05
7   7.634111e+05  7.612056e+05  7.603477e+05  7.605766e+05  7.612683e+05
8   3.913429e+05  3.938308e+05  3.964710e+05  3.987725e+05  4.010843e+05
9   3.370813e+05  3.364464e+05  3.363910e+05  3.367681e+05  3.372721e+05
10  4.629727e+05  4.605311e+05  4.587999e+05  4.573098e+05  4.565938e+05
11  5.849782e+05  5.860765e+05  5.882453e+05  5.903454e+05  5.920735e+05
12  2.752147e+05  2.755834e+05  2.758860e+05  2.765293e+05  2.780351e+05
13  1.914846e+05  1.906598e+05  1.903877e+05  1.904507e+05  1.908797e+05
14  7.197778e+05  7.217282e+05  7.251409e+05  7.273498e+05  7.264971e+05
15  7.313588e+05  7.306278e+05  7.340143e+05  7.417656e+05  7.527001e+05
16  1.813348e+05  1.817018e+05  1.822437e+05  1.825193e+05  1.827507e+05
17  2.800795e+05  2.826208e+05  2.850154e+05  2.873115e+05  2.898924e+05
18  3.187572e+05  3.186551e+05  3.195344e+05  3.211879e+05  3.236661e+05
19  2.768758e+05  2.760335e+05  2.761961e+05  2.771441e+05  2.789386e+05
20  2.385101e+05  2.388666e+05  2.394343e+05  2.399516e+05  2.409561e+05
21  1.179259e+06  1.177197e+06  1.177328e+06  1.178104e+06  1.180168e+06
22  4.933284e+05  4.969126e+05  5.008205e+05  5.046535e+05  5.089392e+05
23  4.719658e+05  4.720293e+05  4.729870e+05  4.743279e+05  4.756925e+05
24  6.908208e+05  6.879965e+05  6.876152e+05  6.880650e+05  6.896861e+05
25  7.190999e+05  7.222122e+05  7.258579e+05  7.288286e+05  7.311463e+05
26  3.547768e+05  3.553583e+05  3.560167e+05  3.567388e+05  3.581706e+05
27  2.770206e+05  2.771414e+05  2.782991e+05  2.797482e+05  2.814312e+05
28  7.591309e+05  7.618621e+05  7.655927e+05  7.676440e+05  7.675120e+05
29  8.615470e+05  8.626187e+05  8.691013e+05  8.808361e+05  8.963798e+05
30  2.434156e+05  2.437652e+05  2.446415e+05  2.455405e+05  2.464633e+05
31  2.949988e+05  2.965959e+05  2.982844e+05  3.001335e+05  3.022384e+05
32  3.991497e+05  3.995222e+05  4.011474e+05  4.038178e+05  4.070253e+05
33  3.822063e+05  3.814430e+05  3.819704e+05  3.834973e+05  3.859914e+05
34  2.889824e+05  2.895932e+05  2.902151e+05  2.908260e+05  2.916313e+05
35  1.517516e+06  1.514403e+06  1.514029e+06  1.514069e+06  1.516603e+06
36  5.921003e+05  5.967425e+05  6.023498e+05  6.083889e+05  6.147977e+05
37  5.901247e+05  5.906221e+05  5.922449e+05  5.941141e+05  5.958330e+05
38  8.828606e+05  8.816454e+05  8.837263e+05  8.871088e+05  8.918664e+05
39  7.136739e+05  7.193038e+05  7.249184e+05  7.295691e+05  7.336271e+05
40  3.714051e+05  3.715724e+05  3.715270e+05  3.713584e+05  3.716596e+05
41  3.335113e+05  3.345476e+05  3.364910e+05  3.385324e+05  3.403054e+05

      2023-09-30
0   5.689674e+05
1   5.873821e+05
2   1.299547e+05
3   2.417185e+05
4   2.547366e+05
5   1.951222e+05
6   1.721653e+05
7   7.610540e+05
8   4.032239e+05
9   3.376411e+05
10  4.564527e+05
11  5.929621e+05
12  2.797841e+05
13  1.911680e+05
14  7.236179e+05
15  7.641775e+05
16  1.826371e+05
17  2.921892e+05
18  3.260609e+05
19  2.807750e+05
20  2.415634e+05
21  1.181742e+06
22  5.127861e+05
23  4.764781e+05
24  6.913151e+05
25  7.324002e+05
26  3.599015e+05
27  2.825867e+05
28  7.654063e+05
29  9.120778e+05
30  2.469522e+05
31  3.037498e+05
32  4.100548e+05
33  3.884212e+05
34  2.921083e+05
35  1.518455e+06
36  6.206861e+05
37  5.972092e+05
38  8.962632e+05
39  7.363314e+05
40  3.723548e+05
41  3.412850e+05

[42 rows x 69 columns]

In [9]:
combined_df.to_csv('combined_housing_data.csv', index=False)